url: http://elliptips.info
name: Elliptips
description: Web, Linux, OSX, astuces et tutos...
title: Elliptips
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog

# Custom config
source: ./src
destination: ./dist
keep_files: [assets] # Jekyll wont be in charge of assets folder

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json

# Infos
twitter_username: robin_parisi
github_username:  robinparisi
